### ISSUE TITLE
Possible bug on v0.6 (20160311)

### ISSUE THREAD

**Issue by papa-gene** [d0k3/OTPHelper#1]
Hi d0k3!

When using v0.6, I am unable to restore a 2.1.0E emuNAND file to a 9.2.0-20E sysNAND, when I try to do it I get the following error: 
"NAND header not recognized"

This also happens when trying the new "Copy emuNAND to sysNAND" option, and when creating an emuNAND backup and then trying to restore it back to emuNAND. Haven't tried other features.

v0.5 works well.

**Comment by d0k3** [comment]
Already fixed, check the last few commits and the releases.
