### ISSUE TITLE
emuNand backup is silently cut if SD is out of space

### ISSUE THREAD

**Issue by lprot** [d0k3/OTPHelper#10]
I was making sysNand backup and emuNand backup. I got emuNand 766Mb only because free space on SD gone. Hope you will add the check and nobody will lost emuNand original beside me :)

**Comment by d0k3** [comment]
It's almost impossible that happened without an error message, maybe you missed it? If you can, try this again (making a backup with not enough space on the SD.

**Comment by d0k3** [comment]
There should have been an error message in your case, too, but this commit adds more checking for SD free space: https://github.com/d0k3/OTPHelper/commit/76204fd89d1dacb1a5a3fa421705f4d4de81c2de

If you can, please test again.

**Comment by lprot** [comment]
Thanks!
