### ISSUE TITLE
PLS helpme!

### ISSUE THREAD

**Issue by headlessdoll** [d0k3/OTPHelper#11]
Hi guys, I follow the Plailect guide on a o3ds and everything work until section IV:
when i do the backup of sysNAND_original.bin and emuNAND_original.bin the size is always wrong...instead of 943MB the backup is 965MB. what can i do?

**Comment by mariogamer2** [comment]
Are you sure that it is not a file explorer bug?

Verify hem by restoring emuNAND with D9WIP

2016-04-16 10:37 GMT-04:00 headlessdoll <notifications@github.com>:

**Comment by headlessdoll** [comment]
I tried to restore emuNAND with D9Wip and everything is gone be fine! 
So can I use this backup to proceed?

**Comment by d0k3** [comment]
Yup, just use it. One thing you can try, tough... Use D9WIPs maintenance options -> system info. What size does it display for the NAND?

**Comment by headlessdoll** [comment]
The right size! I'm really sorry for disturbing you just for a windows mistake! thank you so so much!

**Comment by d0k3** [comment]
Okay, closing this...
