### ISSUE TITLE
"Press A to overwrite existing file" prompt does not work

### ISSUE THREAD

**Issue by RenaKunisaki** [d0k3/OTPHelper#17]
When making a backup of sysNAND or emuNAND, if you choose the name of an already existing file, it will ask you to press A to confirm overwriting. But since you already had to press A to choose the name, the prompt is immediately dismissed.

**Comment by d0k3** [comment]
Sometimes one button press is registered as two - this happens with the HID registers and is not really fixable. It should not happen often, though. Also, take note that existing files are denoted by a (!). So, should not really be a problem. Leaving this open in case others can comment on that.

**Comment by RenaKunisaki** [comment]
Either way, it should be fixable by changing the logic to check for "A button not pressed for at least ~250ms, then pressed" instead of just "A button pressed". That should work even if the register glitches due to keypad bounce.

**Comment by d0k3** [comment]
Fixed in https://github.com/d0k3/OTPHelper/commit/d0770de57a28997eeace45d7814b2ce378b59fd6
