### ISSUE TITLE
v0.88 does not boot

### ISSUE THREAD

**Issue by Jckf** [d0k3/OTPHelper#18]
On my O3DS OTPHelper v0.88 flashes a red screen, then goes to black and freezes the system, while v0.87 works.

**Comment by akirayuki** [comment]
I second this, I've been trying for I think 30 times already but latest version does not boot on o3ds. V0.87 works though, as OP states.

**Comment by d0k3** [comment]
v0.88 does not change anything in regards to entrypoints when compared to v0.87. It is more likely you're trying a new entrypoint now or something was changed in your system. Just to be safe (and if you haven't already) - could you try OTPHelper v0.87 on the same system and in the same way you tried v0.88?

Also, I need more info. What is your 3DS FW version, how are you starting OTPHelper?

**Comment by akirayuki** [comment]
Mine is 9.2.0-20U and I start OTPHelper using menuhax. And I've tried booting both of them using Menuhax too with the same system, which v0,87 boots on first attempt while v0.88 didn't.

**Comment by Sonrio224** [comment]
I have been getting this to. I have a O3DS and 2DS and both failed to load on v0.88. i used menuhax, OOTHax, and browserhax on ver 9.2U and it wouldn't load no matter what i did. v0.87 loaded just fine for some reason. i was able to get v0.88 to load on my N3DS as a test to see if the update was bad.

**Comment by d0k3** [comment]
Alright, thanks, I'll look into it. If you can compile, could you compile OTPHelper yourself and try again?

**Comment by akirayuki** [comment]
I want to help but I don't know how to compile. I guess the others can do it, hopefully.

**Comment by Sonrio224** [comment]
I no longer have a linux computer to compile with. i would like to help but i don't know how to do that on windows :P

**Comment by d0k3** [comment]
Okay. One other thing that you could try to help, is, try to run one of my other tools (Decrypt9WIP or EmuNAND9, or both) from the same entrypoint. Does it work?

**Comment by Jckf** [comment]
I used menuhax and browserhax on 9.0.0 as entry points when trying this, starting OTPHelper via HBL. Version 0.88 failed ~20 times, while 0.87 worked first try.

**Comment by Sonrio224** [comment]
yea Emunand9 and Decrypt9WIP work. i'm actually a bit worried to continue as i was following this updated guide and it includes .sha files. v0.87 does not. so i will wait... unless it doesn't effect the end result

**Comment by Jckf** [comment]
The other tools start fine, yes. However, there is a problem with Decrypt9 as well, as it won't inject hs.app complaining about hs.enc file size, and again the older version works.

@Sonrio224 You can continue without the sha files. They are "only" used to verify the integrity of the NAND dumps.

**Comment by simbakush** [comment]
I'm so glad I found this. I was stuck on Pt. 4 since v.88 would not boot. thanks for the tip v.87 worked first try.

**Comment by Sonrio224** [comment]
Oh nice. and yea, @Jckf is right. it wont allow hs.app inject, even on the N3DS. i thought opening it was good enough :/

**Comment by d0k3** [comment]
Okay, not trying to get off-topic here, but anyone for whom H&S injection does not work should try an older version of FBI. The newest one (of FBI) seems to have certain problems when injecting.

Also, don't concern yourself too much about missing .SHA files. These are just ignored if they don't exist.

**Comment by d0k3** [comment]
Here's a test build every one of you can try:
https://up1.ca/#2QV_1dKoaBnLdJ2OWhIFKg

Let me know if that works for you!

**Comment by pixilus** [comment]
Test build work like a charm! Thanks!

Had the same problem, n3DS 9.0.0, 0.88 via browserhax+menuhax - always black screen.

**Comment by Sonrio224** [comment]
Yea it works like a charm. was able to do it on 2DS first try

**Comment by Jckf** [comment]
So, did you actually change something, or is this just a recompile, @d0k3?

**Comment by d0k3** [comment]
I changed something, I may have forgotten to set a specfic register for SD card access. Anyways, fixed release is coming up later today.

**Comment by d0k3** [comment]
Also, @Sonrio224, keeping up the off-topic here, but can you try this D9 test build for H&S app injection?
https://up1.ca/#ZPaIp6jfBY5lT91fzhoH8A

**Comment by Sonrio224** [comment]
Worked on N3DS! was able to dump and inject just fine. haven't tested on O3DS tho (tho now i have to undo that to get something i did... but it was worth)

**Comment by d0k3** [comment]
Alright, thank you!

**Comment by rourke** [comment]
Not sure if this adds anything. I'm on 9.2 O3DS. OTPHelper v0.88 didn't work. But your test build worked straight away.

Didn't had any problems with Decrypt9WIP or EmuNAND9.

**Comment by d0k3** [comment]
Alright, fixed in v0.89. Thanks everyone!
