### ISSUE TITLE
OTPhelper fails to see emunand

### ISSUE THREAD

**Issue by StreakSharpshot** [d0k3/OTPHelper#19]
Upon booting it up, It shows the message "EmuNAND ready", but after selecting "NAND Backup & restore", it switches to say "no EmuNAND" I'm wondering what's going on here, cause the emunand runs fine.

**Comment by d0k3** [comment]
"EmuNAND ready" means your SD card is ready for an EmuNAND, but no EmuNAND is actually set up. "No EmuNAND" is not a contradiction in that sense.

Now, is it possible that EmuNAND is borked somehow? Try the same in HourGlass9, then report back. Also, what SD card is this, what 3DS type and what did you use to set up the EmuNAND?

**Comment by StreakSharpshot** [comment]
Turns out, it was just cause I was using the one mentioned in Plailect's guide. used a later version and it works okay.

**Comment by d0k3** [comment]
Closing this then, alright.
