### ISSUE TITLE
Otp dosnt load the install option on menu.

### ISSUE THREAD

**Issue by bilbobaggins79** [d0k3/OTPHelper#21]
I have made it to the 5th step and I have placed all the files on my card and when I load the website it's opens otp but there is no install button to run the arm9. I have the verify buttons and backups and inject but there is not a option to run or install anything. I have tried putting the files in there again and goin to try formatting the card and trying again but I don't know what it has to have. To have the install button.

**Comment by ihaveamac** [comment]
I think you copied the wrong `arm9.bin`/`arm11.bin` files. you need to copy the ones for SafeA9LHInstaller, not OTPHelper.

**Comment by bilbobaggins79** [comment]
Thank you so much that was it!
