### ISSUE TITLE
Removed Arm9LoaderHax for the incorrect option in OTPHelper

### ISSUE THREAD

**Issue by Keizel** [d0k3/OTPHelper#23]
I installed Arm9LoaderHax thank to OTPHelper, and I had emuNAND in 11.0. When I moved the emuNAND to sysNAND with OTPHelper, this removed arm9loaderhax. Yes, I know that I would have to be use "Decript9WIP" but I thought that OTPHelper keep arm9loaderhax. Is necessary say with a advice in the option "move emunand to sysnand" that this option NOT keep arm9loaderhax.

**Comment by d0k3** [comment]
OTPHelper was always designed as a one trick tool, not to be used after the A9LH install process. As you wrote yourself, use D9WIP. Also, this tool is deprecated. Closing this new
