### ISSUE TITLE
Incorrect read offset when cloning EmuNAND to SysNAND?

### ISSUE THREAD

**Issue by GerbilSoft** [d0k3/OTPHelper#3]
Looking at commit a9a7fc2, I noticed the call to readsectors::

```
sdmmc_sdcard_readsectors(l_emunand_offset, read_sectors, buffer);
WriteNandSectors(i, read_sectors, buffer);
```

This seems to imply that it's always reading blocks [0, read_sectors) of EmuNAND, then writing them to [i, read_sectors+i), resulting in the first read_sectors blocks of EmuNAND being repeated throughout SysNAND.

**Comment by d0k3** [comment]
Yeah, that's correct. Nobody's perfect ;). It is fixed with the last few commits and in teh newest release.
