### ISSUE TITLE
arm9.bin not included in OTPHelper Release v0.71 (file OTPHelper-20160314-082915.zip)

### ISSUE THREAD

**Issue by charlyzard** [d0k3/OTPHelper#4]
I was following this tutorial here: [https://github.com/Plailect/Guide/wiki/Part-4-%28Getting-the-OTP%29](https://github.com/Plailect/Guide/wiki/Part-4-%28Getting-the-OTP%29)

and noticed that the file arm9.bin is not included in the latest OTPHelper release.

I don't know if it should be included or it's not needed anymore.

It's included in the previous release though.

**Comment by d0k3** [comment]
Check again, the file is in there.
