### ISSUE TITLE
Add support for partial/staged NAND dump/restore

### ISSUE THREAD

**Issue by snoozbuster** [d0k3/OTPHelper#5]
Hey, d0k3! I've got (what I hope is) a small request; would it be possible to add a feature to OTPHelper that allows staged NAND backups? You see, I have a n3ds and a 4gb sd card, and I got to part 4 of Plailect's guide before realizing there was no possible way I could make a NAND backup to my sd card with emunand installed on it; even with nothing on the card I couldn't possibly get to the 1888MB necessary. I looked through a bit of the source and it seems feasible to add a feature to be able to backup in, say, 1GB chunks (or more likely, half the sectors), as well as perform restores in chunks as well. The process would be "backup chunk, unmount sd, wait for user to indicate they're ready, remount and continue" (and similar for restore). This seems like it would work decently well and not be hard to add; if I was at all familar with the 3ds I'd give it a shot myself. 

If you know of any other alternatives or solutions I'd be happy to hear them. I don't know if unmounting the SD card once OTPHelper is loaded and then remounting with a new sd card would work, but that would really only help for backing up sysnand; emunand would still need a different solution. Although, for emunand, would I be able to create a backup/restore by using a tool like `dd` on the emunand partition while the sd card is inserted into my computer? Are there considerations I'd have to take to get that to work? 

Thanks for your help. I don't really know where else I'd go for this information!

**Comment by d0k3** [comment]
This is an issue very specific to your use case, and I won't add routines for partial NAND dumping to this tool, as that might break other things. Micro SD cards are very cheap now, and if you want to do basically anything with that 3DS, you need to get a better one.

If you want to continue with this: Use the EmuNAND -> SysNAND clone feature when going down to 2.1 (instead of backup / restore), and repartition (remove EmuNAND) from your SD card before copying the SysNAND 9.x image to go back up. This is not recommended because this could make it more likely for you to mess up, though.

**Comment by Midar** [comment]
Actually, this is not uncommon at all. I'm facing the exact same problem. With 2 devices. Once you already set up your emuNAND, you also can't move it to a different SD card because of this. You're basically fucked, forever, as the emuNAND is already updated too far, so you can't even copy the emuNAND back to sysNAND and do everything again. Please reopen, this is a serious problem.

**Comment by snoozbuster** [comment]
@Midar: Do you have an SD reader attached to your computer? The emuNAND can be recovered using a computer using a variety of techniques depending on your setup. If you don't have one and can't buy one for some reason, though, you're boned.

**Comment by Midar** [comment]
@snoozbuster Yeah, I have one, but unfortunately, I could nowhere find the correct offsets for dumping the emuNAND of a N3DS with Toshiba NAND using dd - only for O3DS.

**Comment by snoozbuster** [comment]
You have at least one backup of sysnand from back when you started, right? It should be from 512 bytes on the raw card to 512+(size of backup), but in blocks. I'll be home in about three hours and I can give you the dd command I used.

However, there's also NAND redirection to consider. Generally, what this means is you need to take the last 512 bytes of the backup and move them to the front. OTPHelper can verify a backup so be sure to do that before you attempt to restore.

**Comment by Midar** [comment]
Hm, I guess my safest bet here is to buy a new SD card, dd the entire card over and then grow the FAT32. Let me try that tomorrow.

**Comment by snoozbuster** [comment]
That will also work fine. My original understanding was that the emuNAND was stored at the end of the card because of the erroneous way Windows displayed it but it's at the front so yeah, that works fine.

**Comment by d0k3** [comment]
Just use Multi EmuNAND Creator to dump the EmuNAND. Problem solved?

**Comment by Midar** [comment]
@d0k3: Looks like some random Windows binary tool, so it's extremely useless to me. The problem that you cannot dump your emuNAND in any way remains, as not even the offsets to dump using dd are available for an N3DS with Toshiba NAND - only for O3DS.

**Comment by d0k3** [comment]
It's pretty easy. With a little bit of effort you could have found out yourself... 

Search for magic number "NCSD" (better magic number here https://github.com/d0k3/Decrypt9WIP/blob/master/source/decryptor/nand.c). Dump everything from the second sector (offset 0x200) up to and including this sector. When done, place the last sector (the one with NCSD)  at the beginning of the data (insert, not overwrite!). 

If you want to do a service for the community, make a script that works everywhere and release it.
